server:
  port: 80
  servlet:
    context-path: /yoyo
spring:
  banner:
    charset: utf-8
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8


